// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Actions': string;
  'Container': string;
  'Header': string;
  'horizontal': string;
  'hover': string;
  'placeholder': string;
  'scrollable': string;
  'shadow': string;
  'unstyled': string;
}
export const cssExports: CssExports;
export default cssExports;
