// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Grid': string;
  'RangeSlider': string;
}
export const cssExports: CssExports;
export default cssExports;
